# Tarea 4.8

Un colega le entrega a usted archivos de texto con los resultados de una simulación (simulacion.txt). Este archivo contiene tres columnas separadas por espacios tal que cada fila es un dato y las tres columnas son tres propiedades simuladas de ese dato. 

Escriba una función que lea ese archivo de texto y lo vuelva a guardar en un archivo simulacion.hd5 con tres datasets correspondientes a las tres propiedades de cada dato.

Como usted quiere reutilizar esta función para cualquier otro archivo con tres columnas, la función debe tomar el nombre del archivo de texto y el nombre deseado para el nuevo archivo hd5 como argumentos.

El archivo simulacion.txt contiene por ejemplo lo siguiente:

## Solución

In [1]:
import numpy as np
import h5py

Para que este código funcione, necesitamos tener el archivo de texto con los datos en la misma carpeta donde este guardado este código.

In [2]:
def convertir(datos_en_txt, datos_en_hd5):
    
    '''Esta función transforma archivos en .txt de tres columnas a archivos hd5'''
    #leemos el archivo .txt.
    A=np.loadtxt(datos_en_txt)
    print(A)
    
    #separamos las columnas del archivo .txt.
    x,y,z=np.loadtxt(datos_en_txt, unpack=True)

    #Ahora lo grabamos como un archivo hd5.
    with h5py.File(datos_en_hd5, 'w') as file:
        propiedad1 = file.create_dataset('propiedad1', data=x)
        propiedad2 = file.create_dataset('propiedad2', data=y)
        propiedad3 = file.create_dataset('propiedad3', data=z)
    

Ejecutamos y se nos imprimirán los datos originales, y generaremos un nuevo archivo que contenga los datos en hd5.

In [3]:
#Ahora ejecutamos la función anterior con el nombre real de nuestro archivo de texto y el nombre con el cual queramos guardar el archivo hd5.
convertir('simulacion.txt','simulacion_trasformada')

[[3.14159000e-03 2.55768060e+02 4.50140041e+01]
 [6.28318000e-03 3.75281843e+02 2.94777047e+01]
 [9.42477000e-03 4.24669788e+02 2.84352443e+01]
 [1.25663600e-02 4.67632564e+02 2.57622379e+01]
 [1.57079500e-02 4.82091269e+02 1.53026160e+01]
 [1.88495400e-02 4.33766797e+02 1.45024304e+01]
 [2.19911300e-02 4.29906432e+02 7.68952118e+00]
 [2.51327200e-02 3.84074274e+02 5.88065862e+00]
 [2.82743100e-02 3.46487677e+02 5.06204075e+00]]
